# Generated by Django 3.2.6 on 2021-09-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=1000, verbose_name='название')),
                ('text', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
