# Generated by Django 3.2.6 on 2021-09-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('draft', 'Удалено администратором'), ('published', 'Published')], default='None', max_length=10),
        ),
    ]
