# Generated by Django 3.2.6 on 2021-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_alter_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('d', 'Удалено администратором'), ('p', 'Published')], max_length=10),
        ),
    ]
