# Generated by Django 3.2.6 on 2021-09-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0014_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_publish', 'Может публиковать'), ('can_edit', 'Может редактировать')), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
