# Generated by Django 3.2.6 on 2021-10-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0017_alter_news_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_publish', 'Может публиковать'), ('can_edit', 'Может редактировать')), 'verbose_name': 'new', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='title'),
        ),
    ]
