# Generated by Django 3.2.6 on 2021-11-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LodgingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'тип жилища',
                'verbose_name_plural': 'типы жилища',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='заголовок')),
                ('text', models.TextField(blank=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='NumberRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, verbose_name='количество')),
            ],
            options={
                'verbose_name': 'количество комнат',
                'verbose_name_plural': 'количества комнат',
            },
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='название')),
                ('lodgigng_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lodging.lodgingtype')),
                ('numder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_lodging.numberrooms')),
            ],
            options={
                'verbose_name': 'жилище',
                'verbose_name_plural': 'жилища',
            },
        ),
    ]
