# Generated by Django 3.2.6 on 2021-11-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lodging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodging',
            old_name='lodgigng_type',
            new_name='lodging_type',
        ),
    ]
