# Generated by Django 3.2.6 on 2021-09-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_verify', 'Может верифицировать'),), 'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
    ]
