# Generated by Django 3.2.6 on 2021-11-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20211021_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
