# Generated by Django 3.2.6 on 2021-11-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
