# Generated by Django 3.2.6 on 2021-11-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
